### ISSUE TITLE
Undeclared identifier

### ISSUE THREAD

**Issue by Hobbyistpython** [fehlfarbe/python-aruco#11]
Hello,

It looks like I'm getting a bunch of undeclared identifers and would love some help resolving the issues. I've attached the logfile below.
[logfile.txt](https://github.com/fehlfarbe/python-aruco/files/879879/logfile.txt)

**Comment by fehlfarbe** [comment]
Is this the whole log? `./swigbuild.sh` copies the aruco source files to building directory and applies some patches that should prevent these errors. So I think there went something wrong while patching the source files.

**Comment by Hobbyistpython** [comment]
Alright, I'll take a look. I am trying to modify it to work on windows, but I dusted off my linux machine and am making a second attempt.
