### ISSUE TITLE
can I run the example in MS VS 2015?

### ISSUE THREAD

**Issue by ghost** [fehlfarbe/python-aruco#13]
Do not know how to adjust setup.py to run the example in MS VS 2015 as a python project.

**Comment by fehlfarbe** [comment]
Sorry, I have no idea if or how this works with Windows. Maybe it's enough to replace 
```
include_dirs=["C:/opencv2/include", "C:/eigen3/", "."],
                         libraries=["opencv_world.dll", "aruco.dll"],
library_dirs=["C:/opencv2/"]
```
and run setup.py with `python setup.py build --compiler msvc` or so?!
