### ISSUE TITLE
making a pip installation available

### ISSUE THREAD

**Issue by ghost** [fehlfarbe/python-aruco#14]
I am struggling for days now to make aruco be a importable library into my own code.
With your knowledge of python would it not be possible to make a pip-installable version of this library? It would have made my life much easier having that available - in none of the environments I so far tried the aruco is a known library. I am working on W10/64

**Comment by fehlfarbe** [comment]
IIRC it's very easy to make a pip package with a setup.py. But python-aruco isn't a pure Python package. It's just a generated wrapper which depends on other libraries (OpenCV, ArUco). That means you need all dependencies, a compiler and so on. That's easy on Linux, especially with a packet manager but painful on Windows.
I will take a look on this topic but I could take a while...
