### ISSUE TITLE
swigbuild.sh fails

### ISSUE THREAD

**Issue by tkoch96** [fehlfarbe/python-aruco#16]
Hello,

Trying to install this. When I type ./swigbuild.sh I get:

rm: cannot remove 'aruco.py': No such file or directory
...

Hunk #1 FAILED at 35
.....

all the hunks fail

aruco.i:53: Error: Unable to find 'aruco/exports.h'
aruco.i:57: Error: Unable to find 'aruco/checkrectcontour.h'
aruco.i:62: Error: Unable to find 'aruco/levmarq.h'

**Comment by fehlfarbe** [comment]
Did you compile and install ArUco 2.0 at first?

**Comment by tkoch96** [comment]
I installed 3.0, should I install 2.0 instead?

**Comment by fehlfarbe** [comment]
Yes, try it with ArUco 2.0
ArUco 3.0 came out today. Maybe I have some time to update the wrapper at christmas or so.

**Comment by tkoch96** [comment]
Oh what a coincidence lol. Okay thank you :)

**Comment by copypastecopypaste** [comment]
Did this get resolved? Because I run into the same issue with ArUco 3.0
It does not compile the aruco.py file on raspbian. 
I just run into the same issue with ArUco 2.0.19 though. Might be my unskilled way of using the terminal:/

**Comment by fehlfarbe** [comment]
I'm working on ArUco 3.0 wrappers but at the moment there are error messages everywhere :laughing: 
ArUco 2.0.19 should work. Just compile and install (`sudo make install`) ArUco 2.0.19, then run `swigbuild.sh`.
You can also copy the ArUco header files to python-aruco/aruco directory and apply the patch by hand:
```
# copy aruco source code
cp -r /usr/local/include/aruco .
# patch it
patch -p0 < namespaces.patch
```
Then run swig for your python version:
```
# creates wrapper and builds shared library
swig3.0 -c++ -python aruco.i && python setup.py build_ext --inplace
```
or for python3
```
# creates wrapper and builds shared library
swig3.0 -c++ -python -py3 aruco.i && python3 setup.py build_ext --inplace
```

**Comment by fehlfarbe** [comment]
I added ArUco3 support so you can give it a try.

**Comment by copypastecopypaste** [comment]
Thanks man. I will try it tommorrow:)
Im in Tokio timezone
Oliver

**Comment by fehlfarbe** [comment]
I also added pip support. Try to install the package via `sudo -H pip install aruco` :smile:

**Comment by copypastecopypaste** [comment]
so I’ve been trying to install it today again
I am getting an error message upon running the example file from the terminal

 ImportError : No module named ‚aruco‘

I use a virtual environment. So I dunno if its got something to do with that
I installed aruco via Pip3 inside the virtual env (cv)
so its there. Don’t know what I am doing wrong as I am a Raspi noob:/
but still kudos for your work - I feel sry that I am not putting it to good use

**Comment by fehlfarbe** [comment]
Maybe you installed aruco for python3 and start the example with python2?

I tried this with virtualenv:
```
# create and switch to venv
virtualenv -p python3 aruco_virt
source aruco_virt/bin/activate
# try to import aruco without installing it (fails)
python3 -c "import aruco"
#Traceback (most recent call last):
#  File "<string>", line 1, in <module>
# ImportError: No module named 'aruco'
# install aruco via pip
pip install aruco
# retry to import aruco (works)
python3 -c "import aruco"
```

It seems there is an error with Python2 because the aruco.py files are different for Python2/3. I will try to fix it but Python3 should work.

**Comment by copypastecopypaste** [comment]
My default version is py3
I got no clue what it could be:/
Maybe I will flash the sd anew.

Oliver

**Comment by fehlfarbe** [comment]
That's weird...I tried with a fresh install (Ubuntu 16.04) and it works with Python3 and virtualenv. Was there an error message while installing aruco? Is aruco in `your_virtual_env/lib/python3.5/site-packages`? There should be an `aruco.py` and `_aruco.cpython-35m-x86_64-linux-gnu.so` (or similar) and a directory `aruco-3.0.4.dist-info`

**Comment by copypastecopypaste** [comment]
Yeah … I guess I had not much of a clue on how to install stuff.
I moved the files to the right place now. (They where in the py2.7 lib folder
But now I am getting an import Error on 
libaruco.so.2.0
I located that one in the lib folder (but not in the one of the virtual environment)
Does this mean I need to mv libaruco.so.2.0 into the lib of the virtual environment?
sry for all the noob stuff

**Comment by fehlfarbe** [comment]
is `libaruco.so.2.0` in `/usr/local/lib`? If yes, try `sudo ldconfig` and then start your example or add the directory to your library path: `export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH` then run the example in the same terminal.
