### ISSUE TITLE
issue about installation

### ISSUE THREAD

**Issue by Myzhencai** [fehlfarbe/python-aruco#18]
I do followed the instruction and no matter in python2.7 or python3.4 I still get the same error ,by the way I  am using ubuntu14.04 .can anyone help with ?

 #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /usr/include/python2.7/numpy/ndarrayobject.h:26:0,
                     from /usr/include/python2.7/numpy/arrayobject.h:4,
                     from aruco_wrap.cxx:5292:
    /usr/include/python2.7/numpy/__multiarray_api.h:1574:0: warning: "PyArray_SetBaseObject" redefined [enabled by default]
     #define PyArray_SetBaseObject \
     ^
    aruco_wrap.cxx:5284:0: note: this is the location of the previous definition
      #define PyArray_SetBaseObject(arr, x) (PyArray_BASE(arr) = (x))
     ^
    In file included from aruco_wrap.cxx:5304:0:
    src/include/aruco/levmarq.h:31:22: fatal error: Eigen/Core: 没有那个文件或目录
     #include <Eigen/Core>
                          ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-EY0OU_/aruco/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-F6Q9sM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-EY0OU_/aruco/

**Comment by fehlfarbe** [comment]
Install libeigen: `sudo apt-get install libeigen-dev`

**Comment by Myzhencai** [comment]
i will try ,thanks for reply

**Comment by Myzhencai** [comment]
i have run the sudo  apt-get update and then run  sudo apt-get install libeigen-dev but i get the error :   
[sudo] password for gaofei: 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 未发现软件包 libeigen-dev
means that did not find the libeigen-dev ,sorry for the Chinese ,this might be the reason i installed the python-opncv-contrib by pip so this can not use the numpy correctly,would you please share some suggestions? many thanks.

**Comment by fehlfarbe** [comment]
My bad, it's `sudo apt-get install libeigen3-dev`. I think this error
```
In file included from aruco_wrap.cxx:5304:0:
src/include/aruco/levmarq.h:31:22: fatal error: Eigen/Core: 没有那个文件或目录
#include <Eigen/Core>
^
```
means that Eigen3 headers aren't found so installing libeigen3-dev should fix this problem.

**Comment by Myzhencai** [comment]
@fehlfarbe  i will try thanks for your reply,have  a nice day .

**Comment by Myzhencai** [comment]
@fehlfarbe thanks for your help i have installed the code and when i import aruco in python3.4 i got the error of : 
Traceback (most recent call last):
  File "/home/gaofei/python-aruco/aruco.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: libopencv_core.so.3.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaofei/python-aruco/aruco.py", line 17, in <module>
    _aruco = swig_import_helper()
  File "/home/gaofei/python-aruco/aruco.py", line 16, in swig_import_helper
    return importlib.import_module('_aruco')
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libopencv_core.so.3.4: cannot open shared object file: No such file or directory
it seems the error occurred cause of the opencv issue ,i might reinstall the opencv as per your instruction but not the official document of opencv.any way thanks for your help.

**Comment by Myzhencai** [comment]
it is ok now,have a nice day!
