### ISSUE TITLE
issue about swigbuild.sh:fatal error: opencv2/core.hpp

### ISSUE THREAD

**Issue by Myzhencai** [fehlfarbe/python-aruco#20]
@fehlfarbe , sorry yesterday i just installed the wrong python-aruco. what i need is the 1.0.3 version,so i just uninstall all the opencv and aruco with the command : 1.for opencv:
make uninstall
cd ..
sudo rm -r build
sudo rm -r /usr/local/include/opencv2 /usr/local/include/opencv /usr/include/opencv /usr/include/opencv2 /usr/local/share/opencv /usr/local/share/OpenCV /usr/share/opencv /usr/share/OpenCV /usr/local/bin/opencv* /usr/local/lib/libopencv*
2.for aruco : sudo make uninstall (in build)
and then i just reinstall the opencv2.10 with the Install-Opencv ,and reinstall the aruco1.0.3
and all of them is fine but when i run the swigbuild.sh i get the error like this:
![2018-01-18 22 44 57](https://user-images.githubusercontent.com/21084423/35103612-575fa652-fca1-11e7-91f9-e0bc3c07852a.png)
can you share some suggestions? do i need reinstall the opencv ?many thanks.

**Comment by fehlfarbe** [comment]
You mean aruco 1.3.0? Did you check out the aruco1.3.0 branch? `git checkout aruco1.3.0`

Looks like openCV headers aren't installed or they aren't installed to `/usr/local/include/opencv2`. Does the file `/usr/local/include/opencv2/core.hpp` exist?

**Comment by Myzhencai** [comment]
@fehlfarbe ,hi.sorry for the delay of reply cause I am in China,here is what i looked for it seems weired ,i will keep tring reinstall opencv ,any progress i will share the message .thanks

**Comment by Myzhencai** [comment]
here is the picture:the core.hpp in the core file
![2018-01-19 08 23 47](https://user-images.githubusercontent.com/21084423/35128723-0a290138-fcf3-11e7-99c5-b6dc558bae44.png)

**Comment by fehlfarbe** [comment]
Checkout didn't work on your screenshot. Go to your `python-aruco` directory and do `git checkout aruco1.3.0`, then retry. I fixed the include paths in aruco header files in 1.3.0.

Greetings from Germany :)

**Comment by Myzhencai** [comment]
@fehlfarbe you are really a awesome man,thanks for your help I have successfully installed the python-aruco,but when i run the example.py i just get the error : but it seems ok .Any way ,thanks for your help ,have a nice day.Greetings from China :-)
![default](https://user-images.githubusercontent.com/21084423/35178986-16701b64-fdcc-11e7-8131-b27cc8e79a9b.png)

**Comment by Myzhencai** [comment]
hi all ,I just find that [https://github.com/fehlfarbe/python-aruco/tree/aruco1.3.0](url)have the modules ,and the instruction is use the [https://github.com/jayrambhia/Install-OpenCV/](url)to install the latest opencv and then download the [https://sourceforge.net/projects/aruco/files/OldVersions/](url)aruco1.3.0 then i just follow the instruction in[https://github.com/fehlfarbe/python-aruco/tree/aruco1.3.0](url)to sudo apt-get install swig3.0(for python3),then I run ./swigbuild.sh: it compiles the shared library (_aruco.so) and generates Python wrappers (aruco.py),run sudo python setup.py install --record log to install the library globally.when i rerun the test_sensor.py it do not raise the issue about this .so I think this should be a solution for the issue .
thanks for the help of  fehlfarbe ,he is really a nice person.
