### ISSUE TITLE
can this be of a bug???

### ISSUE THREAD

**Issue by Myzhencai** [fehlfarbe/python-aruco#22]
python
'''
>>> import aruco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/aruco.py", line 28, in <module>
    _aruco = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/aruco.py", line 24, in swig_import_helper
    _mod = imp.load_module('_aruco', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /opt/conda/lib/python3.6/site-packages/_aruco.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN5aruco15DictionaryBasedE
'''

I have successfully installed the python-aruco1.3.0 and nothing with error but just with some warning .
when I import it in python I got this error .BTW ,my default python is in anaconda. anyone have the idea of this import error? what should i do???

**Comment by Myzhencai** [comment]
@fehlfarbe  can you have a look of this .many thanks.

**Comment by fehlfarbe** [comment]
`undefined symbol` means a library is missing. Can you check with `ldd _aruco.cpython-36m-x86_64-linux-gnu.so`?

**Comment by Myzhencai** [comment]
@fehlfarbe ，here is the result of what you want .please have a look of it ,thanks you.
![image](https://user-images.githubusercontent.com/21084423/35509545-80dc6f88-052f-11e8-9dfe-df14bdbafdb7.png)
![image](https://user-images.githubusercontent.com/21084423/35509589-afd0471a-052f-11e8-94e3-3fa4494ac041.png)

**Comment by fehlfarbe** [comment]
Looks like you generated wrappers for aruco 3 (Dictionarybased is part of Aruco3) . 
Did you checkout aruco1.3.0?

**Comment by Myzhencai** [comment]
@fehlfarbe  yes i do ,i will show you .i install aruco1.3.0

wait for a moment i need to reboot my compute

**Comment by Myzhencai** [comment]
@fehlfarbe ,I will retry it tomorrow,it might be my fault .I will rebuild it in a docker just as per the instruction of your git and share the result to you,thanks for your help.your time is indeed appreciated.
![image](https://user-images.githubusercontent.com/21084423/35514325-cf4dbbf2-0540-11e8-910d-3de213009ff9.png)

**Comment by Myzhencai** [comment]
@fehlfarbe ， i am sorry .it is my fault ,i yesterday copy the opencv file to the docker from my local host but that one used to install with aruco3.0 so when i just delete the build folder of opencv in fact there should be some issue make the result i shared you.
today when i copy a newly download opencv to docker ,everything is fine ,thanks for your help and sorry for the bother.have a nice day.
![screenshot from 2018-01-30 18 58 41](https://user-images.githubusercontent.com/21084423/35562834-a56732a0-05ef-11e8-8d3a-e4e25a346b8c.png)
