### ISSUE TITLE
new issue :ImportError: /usr/local/lib/python3.4/dist-packages/_aruco.cpython-34m.so: undefined symbol: _ZN2cv4readERKNS_8FileNodeERSsRKSs

### ISSUE THREAD

**Issue by Myzhencai** [fehlfarbe/python-aruco#24]
every time i install the opencv and as per the instruction i got different error .that make me down

**Comment by fehlfarbe** [comment]
This symbol should be part of `libopencv_core.so` ( https://docs.opencv.org/3.3.1/de/dd9/classcv_1_1FileNode.html#details ) which is linked in `setup.py` ( https://github.com/fehlfarbe/python-aruco/blob/aruco1.3.0/setup.py#L15 ) so I don't know why this happens ¯\_(ツ)_/¯

**Comment by Myzhencai** [comment]
@fehlfarbe  thanks for your reply . i will try more way to make it . just reinstall os and setup more . i will share the exactly way after that to make others not be like me

**Comment by Myzhencai** [comment]
@fehlfarbe , it is a issue about the version of opencv, we can not use the opencv3.4 for python-aruco1.3.0 finally i get the lesson with 2 disk broken 💯 ,but i really learn well in install opencv : -).
thanks for your help . have a nice day .
