### ISSUE TITLE
How does it Determine the Board Type?

### ISSUE THREAD

**Issue by tkoch96** [fehlfarbe/python-aruco#25]
In your example (example.py), how does the example know which type of board to look for? 
Could you point me to references for looking at how to create/specify a board parameters file or something of the sort?

**Comment by fehlfarbe** [comment]
It looks like they removed the board and replaced it with `MarkerMap`. You can try to load the board with `MarkerMap(filename)` (see: https://github.com/fehlfarbe/python-aruco/blob/master/src/include/aruco/markermap.h#L118) and use the methods of the MarkerMap class. If there are data type errors, please let me know.

**Comment by tkoch96** [comment]
How did you generate the chessboard parameter file in the first place?

**Comment by fehlfarbe** [comment]
The board was created with aruco 1.3.0. Look at `utils_markermap/aruco_create_markermap` in your build directory to create new boards.
