### ISSUE TITLE
dlopen fails when importing aruco

### ISSUE THREAD

**Issue by tuttoweb** [fehlfarbe/python-aruco#26]
Dear all,
I tried to compile aruco and the python wrapper, but the latest one is failing on something.
Specifically, this is what I get when I try to import aruco

```
import aruco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "aruco.py", line 17, in <module>
    _aruco = swig_import_helper()
  File "aruco.py", line 16, in swig_import_helper
    return importlib.import_module('_aruco')
  File "/Users/tuttoweb/miniconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(./_aruco.so, 2): Symbol not found: __ZN5aruco9MarkerMap15convertToMetersEf
  Referenced from: ./_aruco.so
  Expected in: flat namespace
 in ./_aruco.so
```

I googled it without success.
I am using python 2 on MacOS X High Sierra. I found that might be caused by recent versions of bumpy (I downgraded to 1.10 without success).

Do you have any knowledge how to debug this?

**Comment by fehlfarbe** [comment]
Did you install the right version of ArUco and switched to the right branch for the Python wrappers? The master branch is for ArUco 3.

**Comment by tuttoweb** [comment]
Well,
Probably it was my fault. I didn't that wrapper and aruco library were two different libraries to install. When I installed aruco, python import was failing (don't have the message). The best thing to make it work was to compile the whole opencv with contrib modules. I believe you should have a system like opencv, where the python wrapper are included in the main library. Compiling them in a different times can cause problems. Alternatively, just provide bins for osx too ;)

**Comment by fehlfarbe** [comment]
To use this wrapper you have to install OpenCV and ArUco first. I just created the wrapper to use the ArUco library with all features in Python. Bins for OSX and Windows would be nice but I don't have Apple devices nor the time to work on this :grin: 
IIRC the OpenCV ArUco module is a little bit outdated and ArUco 3.0 supports more marker types and should be faster.
