### ISSUE TITLE
cannot find -lacuro

### ISSUE THREAD

**Issue by Nillda** [fehlfarbe/python-aruco#27]
Hi, I am trying to install acuro on my RasPi3 and after installing everything I've encountered a problem saying; `/usr/bin/ld: cannot find -laruco
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-g++' failed with exit status 1
`
while performing the `$ ./swigbuild.sh python3`. I have tried installing both acuro 3.x and 2.x and the error was always the same. Do you have any idea what could be causing this?

**Comment by fehlfarbe** [comment]
Is libaruco.so in `/usr/lib/` or `/usr/local/lib`? Try `sudo ldconfig` and rerun `./swigbuild.sh python3`.

**Comment by Nillda** [comment]
It's in neither of those for some reason, I will try to install it using pip instead of downloading and cmaking it from  their website and let you know once it's done

**Comment by Nillda** [comment]
It's in neither of those for whatever reason. I will try to download and install acuro3 once again

**Comment by Nillda** [comment]
I have just noticed, when cmaking acuro3 I've been using `cmake ..` instead of the recommended `cmake .. -DCMAKE_INSTALL_PREFIX=<pathToInstall>` and `make -j1 install` instead of `make -j4 install` tho that's because my RPi can't handle -j4 and crashes. Can this be the cause?

**Comment by Nillda** [comment]
Updating on my situation here. I've managed to install everything and have libaruco.so `/usr/local/lib`, I also have acuro.py in `/usr/local/lib/python3.5/dist-packages`. What I don't understand tho is why I keep getting `ImportError: No module named 'acuro'`. So I've tried pip installing it for python2.7, now pip freeze says I have acuro v.3.0.4.1 but again, when I try to import it I get the same import error. I do have OpenCV 3.3.0 installed and am able to import it in both python3.5 and 2.7. I've kinda ran out of ideas on what to try next, any suggestion?

**Comment by fehlfarbe** [comment]
Hm that's weird. Some ideas:
- check your `$PYTHONPATH`
- check permissions of `/usr/local/lib/python3.5/dist-packages/aruco.py`

**Comment by Nillda** [comment]
Actually it's not weird. I am just a degenerate who spent two days importing acuro instead of aruco. I still get some import error (`ImportError: /usr/local/lib/python2.7/dist-packages/_aruco.so: undefined symbol: _ZN5aruco9MarkerMap15convertToMetersEf`), but I chose not to use aruco at all in my project and instead go with finding plates with a haar cascade, read the numbers on it and perform some action based on those. Yes, it's not as good solution as acuro, but since the deadline is the next week I don't really have any time to waste. Thanks for all your help tho and hopefully I will be able to revisit your project some time in the future

**Comment by fehlfarbe** [comment]
Always use autocomplete to prevent those mistakes :laughing: 
MarkerMap is part of ArUco 3...maybe it's still linked to ArUco 2.

Unfortunally the license plate detection is behind a paywall but maybe this blog can help you: https://gurus.pyimagesearch.com/lesson-sample-segmenting-characters-from-license-plates/
