### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by neciszhang** [fehlfarbe/python-aruco#28]
Hi,
   I install it and it catch error:
clang: error: unsupported option '-fopenmp'
Can you help me to resolve the problem.  0.0

**Comment by fehlfarbe** [comment]
Is your default compiler `gcc`?
As workaround you can try to remove '-fopenmp' from https://github.com/fehlfarbe/python-aruco/blob/master/setup.py#L18

**Comment by neciszhang** [comment]
@fehlfarbe oh,Thank you!
I finally install it .But i has new question.
When i run 'python3 example/example.py', it catch errors:
 
`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example/example.py", line 5, in <module>
    import aruco
  File "/usr/local/lib/python3.6/site-packages/aruco.py", line 17, in <module>
    _aruco = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/aruco.py", line 16, in swig_import_helper
    return importlib.import_module('_aruco')
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/_aruco.cpython-36m-darwin.so, 2): Symbol not found: __ZN5aruco14CvDrawingUtils10draw3dAxisERN2cv3MatERNS_6MarkerERKNS_16CameraParametersE
  Referenced from: /usr/local/lib/python3.6/site-packages/_aruco.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/_aruco.cpython-36m-darwin.so`

**Comment by fehlfarbe** [comment]
Did you compile and install the ArUco library first?

**Comment by neciszhang** [comment]
Thanks
