### ISSUE TITLE
Get the extrinsics for each marker

### ISSUE THREAD

**Issue by miguelriemoliveira** [fehlfarbe/python-aruco#3]
Hello,

I was wondering if you could share a bit of code on how to get the extrinsics of the marker, because I need the camera to marker transform.

I went through the example.py but there is no such information. Also tried to get it using the calculateExtrinsics function but I can't seem to call it right (complains about the number of arguments / types).

Could you share an example? 

Thanks in advance,

Miguel

**Comment by fehlfarbe** [comment]
Hi,
You have to call the calculateExtrinsics(marker_size_in_meters, CameraParameters) method and then you can read the Marker.Tvec and Marker.Rvec arrays:

```
marker.calculateExtrinsics(0.035, camparam)
print(marker.Tvec)
print(marker.Rvec)
```

See line 47 ff. in 1b474bb3f7b101b627d9ad65e767e58695b01565

**Comment by miguelriemoliveira** [comment]
It works. Thanks for the help.

Miguel
