### ISSUE TITLE
swigbuild.sh error

### ISSUE THREAD

**Issue by noxqs** [fehlfarbe/python-aruco#30]
I am have compiled and installed aruco 3.1.0, python 2.7.5 and opencv 3.4.5

My swigbuild.sh fails with 
`aruco_wrap.cxx:5472:11: fatal error: aruco/markerlabelers/dictionary_based.h: No such file or directory
  #include <aruco/markerlabelers/dictionary_based.h>`

but the file is there:
`# find . | grep -i dictionary_based.h
./aruco-3.1.0/src/dictionary_based.h
./python-aruco/src/include/aruco/markerlabelers/dictionary_based.h`

Could it be an include folder issue ?

Kind regards,
Morgan

**Comment by fehlfarbe** [comment]
Hi Morgan,

can you retry with ArUco 3.0.4? Maybe the includes have changed.

**Comment by noxqs** [comment]
hi FehlFarbe,

I can't find 3.0.4 any more.
Would you happen to have a spare somewhere?

cheers,
Morgan

**Comment by fehlfarbe** [comment]
I added a new branch `aruco-3.0.13` with included aruco source code so downloading and compiling aruco should be obsolete. Can you test it?

```
git clone https://github.com/fehlfarbe/python-aruco.git
cd python-aruco
git checkout aruco-3.0.13
./swigbuild.sh && sudo python setup.py install
python example/example.py
```

**Comment by noxqs** [comment]
Excellent, thank you, that compiled w/o errors.
Running the python example now and experimenting further later.

**Comment by fehlfarbe** [comment]
Perfect! I will update the pip package to the new version.
