### ISSUE TITLE
Error with CvDrawingUtils.draw3dAxis

### ISSUE THREAD

**Issue by Cedaroski** [fehlfarbe/python-aruco#32]
In the example.py, I add:
aruco.CvDrawingUtils.draw3dAxis(frame, marker, camparam)
but with error:

NotImplementedError: Wrong number or type of arguments for overloaded function 'CvDrawingUtils_draw3dAxis'.
 swig/python detected a memory leak of type 'aruco::MarkerDetector::Params *', no destructor found.

Does the funtion draw3dAxis work?

Thanks

**Comment by fehlfarbe** [comment]
Hm overloaded functions sometimes don't work in Python with SWIG generated wrappers. This should work:
```
# calculate marker extrinsics for marker size of 3.5cm
marker.calculateExtrinsics(0.035, camparam)
aruco.CvDrawingUtils.draw3dAxis(frame, camparam, marker.Rvec, marker.Tvec, .1)
```

**Comment by Cedaroski** [comment]
> Hm overloaded functions sometimes don't work in Python with SWIG generated wrappers. This should work:
> 
> ```
> # calculate marker extrinsics for marker size of 3.5cm
> marker.calculateExtrinsics(0.035, camparam)
> aruco.CvDrawingUtils.draw3dAxis(frame, camparam, marker.Rvec, marker.Tvec, .1)
> ```

Thanks! It works
