### ISSUE TITLE
Python3 install errors

### ISSUE THREAD

**Issue by SinclairGurny** [fehlfarbe/python-aruco#34]
Several 'was not declared in this scope errors'.
CV_RETR_LIST, CV_CHAIN_APPROX_NONE, CV_BGR2GRAY, cvSize, CV_TERMCRIT_ITER, CV_TERMCRIT_EPS, cvTermCriteria, cvScalar.

I did get this to install properly (with difficultly) for Python 3 on my previous system: Ubuntu 18. However, it does not work in Manjaro, which is Arch based. I am not sure of the exact reason. Lastly, the pip module aruco also does not work with pip3.

**Comment by fehlfarbe** [comment]
Hi!
I merged the aruco-3.1.2 branch to master and updated the pypi repo (for Python3). Can you try? I think it's some problem with different OpenCV versions. What OpenCV is installed on your system?

**Comment by SinclairGurny** [comment]
Yes, your changes fixed my problem. Thanks!
I am on OpenCV 4.1.0.
