### ISSUE TITLE
how to install aruco 

### ISSUE THREAD

**Issue by yawei798** [fehlfarbe/python-aruco#36]
**install aruco error:**

(tensorflow) jackstan@Jackstan-All-Series:~$ sudo -H pip install aruco
Requirement already satisfied: aruco in /usr/local/lib/python3.5/dist-packages (3.1.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from aruco) (1.16.4)
Requirement already satisfied: opencv-contrib-python in /usr/local/lib/python3.5/dist-packages (from aruco) (4.1.0.25)

(tensorflow) jackstan@Jackstan-All-Series:~$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import aruco
>>> detector = aruco.MarkerDetector()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aruco' has no attribute 'MarkerDetector'

**Comment by fehlfarbe** [comment]
Hm that's weird. Can you please post the output of `python -c "import aruco; print(aruco.__dict__)"`?

**Comment by wakeguo** [comment]
^C(tensorflow) jackstan@Jackstan-All-Series:~$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aruco
>>> print(aruco.__dict__)
{'__name__': 'aruco', '__doc__': None, '__package__': 'aruco', '__loader__': <_frozen_importlib_external._NamespaceLoader object at 0x7f96469764e0>, '__spec__': ModuleSpec(name='aruco', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['/home/jackstan/aruco', '/home/jackstan/aruco'])), '__path__': _NamespacePath(['/home/jackstan/aruco', '/home/jackstan/aruco'])}
>>> 

Thank you

**Comment by wakeguo** [comment]
(tensorflow) jackstan@Jackstan-All-Series:~$ cd /home/jackstan/aruco
(tensorflow) jackstan@Jackstan-All-Series:~/aruco$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aruco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aruco'
>>>

**Comment by wakeguo** [comment]
(tensorflow) jackstan@Jackstan-All-Series:~/aruco/python$ sudo -H pip install aruco-3.1.2.0.tar.gz
Processing ./aruco-3.1.2.0.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from aruco==3.1.2.0) (1.16.4)
Requirement already satisfied: opencv-contrib-python in /usr/local/lib/python3.5/dist-packages (from aruco==3.1.2.0) (4.1.0.25)
Building wheels for collected packages: aruco
  Building wheel for aruco (setup.py) ... done
  Created wheel for aruco: filename=aruco-3.1.2.0-cp35-cp35m-linux_x86_64.whl size=618275 sha256=cc7928174dd4995308059579c8b2dd1526272fc90ca45b56f6897bd66215c8ee
  Stored in directory: /root/.cache/pip/wheels/51/e9/21/c7d9c077c2a03ff4cb7c7f4e6c025893158e34c77907fbb471
Successfully built aruco
Installing collected packages: aruco
  Found existing installation: aruco 3.1.2.0
    Uninstalling aruco-3.1.2.0:
      Successfully uninstalled aruco-3.1.2.0
Successfully installed aruco-3.1.2.0
(tensorflow) jackstan@Jackstan-All-Series:~/aruco/python$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aruco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aruco'

**Comment by yawei798** [comment]
Thank you, I have solved the problem. But can't generate a fractal marker tag, can you tell me how to generate a different ID fractal marker tag?


a = aruco.FractalMarkerSet()
a.FRACTAL_2L_6
aruco.FractalMarkerLabeler_create("test.jpg", a)

**Comment by fehlfarbe** [comment]
Sorry, I never tried to generate markers with Python. I always use arucos `fractal_print_marker` in `build/utils_fractal`.
