### ISSUE TITLE
2D distance camera to fractal marker on x-y plane

### ISSUE THREAD

**Issue by a-altug** [fehlfarbe/python-aruco#44]
Hi,

It's good to see 3.1.12 is master and easy to install via pip :)
Thank you.

I will use fractal marker to make land a multicopter.

.getCenter method returns center of marker like kind of pixel map.
on the other hand rvec and tvec are includes radian values except tvec[2][0] (z-axis)
Is there any method (in library) to get distance between camera and fractal marker on 2D.(x, y)

**Comment by fehlfarbe** [comment]
It works on my machine and in the docker container so I hope it will work on other machines :+1: 

If you want the distance between camera and center of the marker you just need the magnitude of tvec:

`mag = math.sqrt(tvec[0]**2 + tvec[1]**2 + tvec[2]**2)`

Assuming your intrinsics are well calibrated and converted to meters, the result is also in meters.

If you want to calculate the 3D position from the 2D pixel coordinates, look at this Stackoverflow post: https://stackoverflow.com/questions/12299870/computing-x-y-coordinate-3d-from-image-point

or at this post https://stackoverflow.com/questions/34140150/reverse-of-opencv-projectpoints (there is Python code below).
