### ISSUE TITLE
pip install still not working with python3 

### ISSUE THREAD

**Issue by vkuehn** [fehlfarbe/python-aruco#46]
it still pussly me when going from one machine to another as pip install arcuo does not work with python aruco. 
It's quite some time since python 2 support ended completely.

Any plans to make that work ?

**Comment by vkuehn** [comment]
meantime I made it work ., still odd habits sometimes during installation

**Comment by fehlfarbe** [comment]
Hey sorry, I have too much work at the moment to support this repo. I'm glad you found a solution :+1:
