### ISSUE TITLE
Error while installation 

### ISSUE THREAD

**Issue by gaganacharya1995** [fehlfarbe/python-aruco#5]
While running swigbuild.sh script in Ubuntu terminal, I am getting an error 

aruco_wrap.cxx:5227:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
                               ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any idea what's happening? I am installing this in a virtual environment with numpy installed in it.

**Comment by fehlfarbe** [comment]
Try `locate arrayobject.h` in Bash, export the location to CFLAG environment variable and run ./swigbuild again.

Example for my system:
```
kolbe@edgi ~ $ locate arrayobject.h
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h
```
```
export CFLAGS=-I/usr/lib/python2.7/dist-packages/numpy/core/include/
./swigbuild
```
If this doesn't work, please post your Ubuntu version, so I can figure it out with a clean install.

**Comment by gaganacharya1995** [comment]
I used the below commands
 export CFLAGS=-I/usr/local/lib/python2.7/dist-packages/numpy/core/include/
./swigbuild.sh
 
So now I am not getting the previous error. Instead I am getting a new error

collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1

I am using Ubuntu 14.04.4

**Comment by fehlfarbe** [comment]
Did you install numpy with `pip` or with `apt-get`?
It seems that pip doesn't install the numpy headers so I installed numpy with
`sudo apt-get install python-numpy` and now it's compiling.
