### ISSUE TITLE
installation troubles

### ISSUE THREAD

**Issue by MessMaker236** [fehlfarbe/python-aruco#6]
The following error when running the example:

`pi@raspberrypi:~/aruco/example $ sudo python example.py
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    import aruco
  File "/usr/local/lib/python2.7/dist-packages/aruco.py", line 28, in <module>
    _aruco = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/aruco.py", line 24, in swig_import_helper
    _mod = imp.load_module('_aruco', fp, pathname, description)
ImportError: libaruco.so.2.0: cannot open shared object file: No such file or directory`

I am using a raspberry pi 3, and set up opencv and numpy as the PiImageSearch tutorial.

I compiled and installed ArUco 2.0.19. If this needs to change, could you let me know how to do that, because when I try to install 1.3.0 I get an error probably because the other version is still installed. 

Anyway thanks for your help

**Comment by fehlfarbe** [comment]
Hi,
did `swigbuild.sh` and `sudo python setup.py install` work with ArUco 2.x? It should only work with version 1.3.0 at the moment. Maybe I can test it with version 2.0.19 the next days.

**Comment by MessMaker236** [comment]
Hey fehlfarbe,
ArUco 2.x did not work. So I uninstalled it and got 1.3.0.
However after doing `swigbuild.sh `and `sudo python setup.py install` I still get a similar error to ^.
Chances are that I messed everything when I had the newer Aruco, so I will start over with a fresh everything unless you have any tips?
Thanks!

**Comment by fehlfarbe** [comment]
Hey MessMaker,
I had some time to create wrappers for aruco 2.0.19. So you can try to compile the new wrappers with aruco2.

If you want to use aruco 1.3.0, check if all symlinks/arcuo libs are fine with `ls -l /usr/local/lib/libaruco*` and update ld linker library with `sudo ldconfig`. It looks that the wrapper is linked against aruco2 instead of aruco1.3.0

**Comment by MessMaker236** [comment]
Hey fehlfarbe,
I updated ld linker library with sudo ldconfig and it finally works!
I am still using aruco1.3.0, but in the future might switch to 2.x
Thank you so much for this!!!
