### ISSUE TITLE
Draw Markers

### ISSUE THREAD

**Issue by MessMaker236** [fehlfarbe/python-aruco#7]
Is it possible to use the drawMarker function to create ArUco markers with this wrapper?
If not, its ok, but how should I go about creating markers?
Thanks

**Comment by MessMaker236** [comment]
Sorry for the extremely nubie issue.
Draw markers here: http://terpconnect.umd.edu/~jwelsh12/enes100/markergen.html

**Comment by fehlfarbe** [comment]
Ther is also the program `aruco_print_marker` in `aruco-2.0.19/build/utils/` :)
