### ISSUE TITLE
ArUco 2.0.19 issue

### ISSUE THREAD

**Issue by MessMaker236** [fehlfarbe/python-aruco#8]
Hey fehlfarbe,
I just got a fresh install of everything, to test the recent changes you made.
I chose ArUco 2.0.19, python2, and opencv 3.1.0,
however upon running `swigbuild.sh`, the following error:
```
In file included from aruco_wrap.cxx:5209:0:
./aruco/levmarq.h:3:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

**Comment by fehlfarbe** [comment]
ArUco 2.0 needs the Eigen library.
Did you install libeigen3-dev: `sudo apt-get install libeigen3-dev`?
Does the directory `/usr/include/eigen3/Eigen` exist?

**Comment by MessMaker236** [comment]
That was exactly the issue.
I was wrong to believe that eigen3 was included with the ArUco library.
Maybe this should be in the README?
Thanks again for your assistance 👍
